### ISSUE TITLE
'00:00:1' is not a valid time

### ISSUE THREAD

**Issue by Balaarizalu** [dinochen1983/DINOETE#1]
Hello Mr Dino Chen, First I want to say a big thank you for this software. I want to convey an issue regarding ETESEC on my computer, where when I try to open the ETESEC software, it just opened and then an error message appears as shown in the screenshot.
Maybe there's something wrong with the way I'm running the software or is there something I'm missing?
Best Regard, Bala Arizalu.
![image](https://user-images.githubusercontent.com/11691775/167333948-610da6c3-38bd-42a4-ad9f-b3ed40f65a8c.png)

**Comment by dinochen1983** [comment]
the software required a license.
